### ISSUE TITLE
PSDD Modal bug

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#91] opened 2021-07-10 11:24 UTC
After casting PSDD at opponent's Monster there should be a "Choose Target" button. But it doesn't show.
It shows only on the next turn when the monster is already yours

**Comment by Pz1c** [comment] 2021-07-12 12:54
are you get this in 1.9.0.4?
can't reproduce(

**Comment by Prulon** [comment] 2021-07-12 13:29
Yes.
How to reproduce:
1 open a game with bot
2 Let it bring a monster
3 cast psdd at monster
4 send
5 click on monster and open modal

Expected result:
Modal with choose target button

Actual result
Modal with no button

**Comment by Pz1c** [comment] 2021-07-12 13:48
oh, I suppose button not appear just after charm)
I'll check

**Comment by Pz1c** [comment] 2021-07-13 09:57
test battle 86089
preparing 4 turn, bot prepare summon goblin and I choose D for left hand cast Charm on goblin and after choosing monster appear window with available "choose target" button
turn 4 results
goblin summoned, and goes under my control, after clicking on monster button "choose target" available
perhaps, bug already fixed by some other fix and not reproducing on my "dev" version

lets go production and check)

**Closed by Pz1c** 2021-07-13 09:57 UTC
Labels: bug
