### ISSUE TITLE
End game sometimes shows wrong result

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#174] opened 2022-04-01 09:41 UTC
For example on our recent game 87026
the conclusion is: "Draw vs. Galbarad" and also when I go into the game it doesn't show the last turns and doesn't show victory

**Comment by Pz1c** [comment] 2022-04-01 09:52
yep I got same problem(
but can't found root cause yet(

**Comment by Pz1c** [comment] 2022-04-01 13:36
should be fixed in 1.9.7.5

**Closed by Pz1c** 2022-04-01 13:36 UTC
Labels: bug
