### ISSUE TITLE
Possibly critical bug

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#292] opened 2023-06-09 22:21 UTC
After I created a new test player, I clicked on the '>' in the tutorial, 
but when I got the 'P/P' it didn't go through, instead when I click the '>' the chat opens - so the wrong part of the screen gets my click

**Comment by Pz1c** [comment] 2023-06-10 11:59
should be fixed with 2.1.2, I hope, because I can't reproduce and try to fix place where problem can appear in blindly

**Closed by Pz1c** 2023-06-10 12:00 UTC
Labels: bug
